# Taken from https://github.com/pygae/lean-ga/blob/master/.github/workflows/lean_doc.yml

# Run this workflow every time a new commit pushed to the repository but only on the master branch
on:
  push:
    branches:
      - master

jobs:
  build_docs:
    runs-on: ubuntu-latest
    name: Build docs
    steps:

    - name: 📁 Checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 🔧 Install elan
      run: |
        set -o pipefail
        curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
        ~/.elan/bin/lean --version
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: 🐍 Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: 📁 Checkout Lean's doc-gen
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: leanprover-community/doc-gen
        path: doc-gen

    - name: 🐍 Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r doc-gen/requirements.txt
        ls doc-gen

    - name: ✏️ Mangle paths for doc-gen
      run: |
        lean_version="$(sed '/^lean_version/!d;s/.*"\(.*\)".*/\1/' leanpkg.toml)"
        mathlib_git_hash="$(sed '/rev/!d;s/.*"\([a-z0-9]*\)".*/\1/' leanpkg.toml)"
        cd doc-gen
        sed -i "s/rev = \"\S*\"/rev = \"$mathlib_git_hash\"/" leanpkg.toml

        # Force doc_gen project to match the Lean version used in CI.
        # If they are incompatible, something in doc_gen will fail to compile,
        # but this is better than trying to recompile all of mathlib.
        elan override set "$lean_version"

        leanproject get-mathlib-cache
        echo -e "path ../src" >> leanpkg.path
        cat leanpkg.path
        (cd ../src;
        find "." -name \*.lean -not -name all.lean \
          | sed 's,^\./,,;s,\.lean$,,;s,/,.,g;s,^,import ,' \
          | sort >./all.lean)

        cat ../src/all.lean
        lean --path

    - name: 📝 Export Lean symbol information
      run: |
        cd doc-gen
        lean -v
        # the json and diagnostics are emitted on stdout, but the json is always the last (very long) line.
        lean src/entrypoint.lean > export.json || true
        head -n -1 export.json
        tail -n1 export.json > export2.json
        rm export.json
        mv export2.json export.json
        head -c1000 export.json

    - name: 📚 Build HTML docs
      run: |
        cd doc-gen
        python3 \
          -c "import print_docs; del print_docs.extra_doc_files[:]; print_docs.copy_yaml_files = lambda p: None; print_docs.library_link_roots['igl2020'] = 'https://github.com/vaibhavkarve/igl2020/blob/$GITHUB_SHA/src/'; print_docs.main()" \
          -r .. -w 'https://vaibhavkarve.github.io/igl2020-docs/' -t built-docs

    - name: 🔑 Install SSH Client
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


    - name: 🚀 Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        single-commit: true
        repository-name: vaibhavkarve/vaibhavkarve.github.io
        branch: master # The branch the action should deploy to.
        folder: doc-gen/built-docs # The folder the action should deploy.
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        target-folder: igl2020-docs  # The folder to push contents to.
